# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 039f95d3c24a7c5dae06db97353b9d2bb1fe4f4204a4390475bb69279086ac2ede1aa6b23a695d88a19c44468328985f3935bf3e153cb9eb7fdf5b6b99444276

test:
  secret_key_base: 5fd959ba4603130c3cbeb9d6467d026fc08ef5887d03f6b9d1778d2e70c3b0ccdcd5e77a7d0c0d0565db7750b79bde3b917b12c9f28af6ed47b44670d0250aa6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
