# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)

alabama_category = Category.where(name: 'Alabama').first_or_create(name: 'Alabama')
alaska_category = Category.where(name: 'Alaska').first_or_create(name: 'Alaska')
arizona_category = Category.where(name: 'Arizona').first_or_create(name: 'Arizona')
arkansas_category = Category.where(name: 'Arkansas').first_or_create(name: 'Arkansas')
california_category = Category.where(name: 'California').first_or_create(name: 'California')
colorado_category = Category.where(name: 'Colorado').first_or_create(name: 'Colorado')
connecticut_category = Category.where(name: 'Connecticut').first_or_create(name: 'Connecticut')
delaware_category = Category.where(name: 'Delaware').first_or_create(name: 'Delaware')
florida_category = Category.where(name: 'Florida').first_or_create(name: 'Florida')
georgia_category = Category.where(name: 'Georgia').first_or_create(name: 'Georgia')
hawaii_category = Category.where(name: 'Hawaii').first_or_create(name: 'Hawaii')
idaho_category = Category.where(name: 'Idaho').first_or_create(name: 'Idaho')
illinois_category = Category.where(name: 'Illinois').first_or_create(name: 'Illinois')
indiana_category = Category.where(name: 'Indiana').first_or_create(name: 'Indiana')
iowa_category = Category.where(name: 'Iowa').first_or_create(name: 'Iowa')
kansas_category = Category.where(name: 'Kansas').first_or_create(name: 'Kansas')
kentucky_category = Category.where(name: 'Kentucky').first_or_create(name: 'Kentucky')
louisiana_category = Category.where(name: 'Louisiana').first_or_create(name: 'Louisiana')
maine_category = Category.where(name: 'Maine').first_or_create(name: 'Maine')
maryland_category = Category.where(name: 'Maryland').first_or_create(name: 'Maryland')
massachusetts_category = Category.where(name: 'Massachusetts').first_or_create(name: 'Massachusetts')
michigan_category = Category.where(name: 'Michigan').first_or_create(name: 'Michigan')
minnesota_category = Category.where(name: 'Minnesota').first_or_create(name: 'Minnesota')
mississippi_category = Category.where(name: 'Mississippi').first_or_create(name: 'Mississippi')
missouri_category = Category.where(name: 'Missouri').first_or_create(name: 'Missouri')
montana_category = Category.where(name: 'Montana').first_or_create(name: 'Montana')
nebraska_category = Category.where(name: 'Nebraska').first_or_create(name: 'Nebraska')
nevada_category = Category.where(name: 'Nevada').first_or_create(name: 'Nevada')
newhampshire_category = Category.where(name: 'New Hampshire').first_or_create(name: 'New Hampshire')
newjersey_category = Category.where(name: 'New Jersey').first_or_create(name: 'New Jersey')
newmexico_category = Category.where(name: 'New Mexico').first_or_create(name: 'New Mexico')
newyork_category = Category.where(name: 'New York').first_or_create(name: 'New York')
northcarolina_category = Category.where(name: 'North Carolina').first_or_create(name: 'North Carolina')
northdakota_category = Category.where(name: 'North Dakota').first_or_create(name: 'North Dakota')
ohio_category = Category.where(name: 'Ohio').first_or_create(name: 'Ohio')
oklahoma_category = Category.where(name: 'Oklahoma').first_or_create(name: 'Oklahoma')
oregon_category = Category.where(name: 'Oregon').first_or_create(name: 'Oregon')
puertorico_category = Category.where(name: 'Puerto Rico').first_or_create(name: 'Puerto Rico')
pennsylvania_category = Category.where(name: 'Pennsylvania').first_or_create(name: 'Pennsylvania')
rhodeisland_category = Category.where(name: 'Rhode Island').first_or_create(name: 'Rhode Island')
southcarolina_category = Category.where(name: 'South Carolina').first_or_create(name: 'South Carolina')
southdakota_category = Category.where(name: 'South Dakota').first_or_create(name: 'South Dakota')
tennessee_category = Category.where(name: 'Tennessee').first_or_create(name: 'Tennessee')
texas_category = Category.where(name: 'Texas').first_or_create(name: 'Texas')
utah_category = Category.where(name: 'Utah').first_or_create(name: 'Utah')
vermont_category = Category.where(name: 'Vermont').first_or_create(name: 'Vermont')
virginia_category = Category.where(name: 'Virginia').first_or_create(name: 'Virginia')
washington_category = Category.where(name: 'Washington').first_or_create(name: 'Washington')
westvirginia_category = Category.where(name: 'West Virginia').first_or_create(name: 'West Virginia')
wisconsin_category = Category.where(name: 'Wisconsin').first_or_create(name: 'Wisconsin')
wyoming_category = Category.where(name: 'Wyoming').first_or_create(name: 'Wyoming')

Subcategory.where(name: 'Anchorage', category_id: alaska_category.id).first_or_create(name: 'Anchorage', category_id: alaska_category.id)
Subcategory.where(name: 'Fairbanks', category_id: alaska_category.id).first_or_create(name: 'Fairbanks', category_id: alaska_category.id)

Subcategory.where(name: 'Anniston', category_id: alabama_category.id).first_or_create(name: 'Anniston', category_id: alabama_category.id)
Subcategory.where(name: 'Auburn', category_id: alabama_category.id).first_or_create(name: 'Auburn', category_id: alabama_category.id)
Subcategory.where(name: 'Birmingham', category_id: alabama_category.id).first_or_create(name: 'Birmingham', category_id: alabama_category.id)
Subcategory.where(name: 'Daphne', category_id: alabama_category.id).first_or_create(name: 'Daphne', category_id: alabama_category.id)
Subcategory.where(name: 'Decatur', category_id: alabama_category.id).first_or_create(name: 'Decatur', category_id: alabama_category.id)
Subcategory.where(name: 'Dothan', category_id: alabama_category.id).first_or_create(name: 'Dothan', category_id: alabama_category.id)
Subcategory.where(name: 'Florence', category_id: alabama_category.id).first_or_create(name: 'Florence', category_id: alabama_category.id)
Subcategory.where(name: 'Gadsden', category_id: alabama_category.id).first_or_create(name: 'Gadsden', category_id: alabama_category.id)
Subcategory.where(name: 'Huntsville', category_id: alabama_category.id).first_or_create(name: 'Huntsville', category_id: alabama_category.id)
Subcategory.where(name: 'Mobile', category_id: alabama_category.id).first_or_create(name: 'Mobile', category_id: alabama_category.id)
Subcategory.where(name: 'Montgomery', category_id: alabama_category.id).first_or_create(name: 'Montgomery', category_id: alabama_category.id)
Subcategory.where(name: 'Tuscaloosa', category_id: alabama_category.id).first_or_create(name: 'Tuscaloosa', category_id: alabama_category.id)

Subcategory.where(name: 'Conway', category_id: arkansas_category.id).first_or_create(name: 'Conway', category_id: arkansas_category.id)
Subcategory.where(name: 'Fayetteville', category_id: arkansas_category.id).first_or_create(name: 'Fayetteville', category_id: arkansas_category.id)
Subcategory.where(name: 'Fort Smith', category_id: arkansas_category.id).first_or_create(name: 'Fort Smith', category_id: arkansas_category.id)
Subcategory.where(name: 'Hot Springs', category_id: arkansas_category.id).first_or_create(name: 'Hot Springs', category_id: arkansas_category.id)
Subcategory.where(name: 'Jonesboro', category_id: arkansas_category.id).first_or_create(name: 'Jonesboro', category_id: arkansas_category.id)
Subcategory.where(name: 'Little Rock', category_id: arkansas_category.id).first_or_create(name: 'Little Rock', category_id: arkansas_category.id)
Subcategory.where(name: 'Pine Bluff', category_id: arkansas_category.id).first_or_create(name: 'Pine Bluff', category_id: arkansas_category.id)

Subcategory.where(name: 'Avondale', category_id: arizona_category.id).first_or_create(name: 'Avondale', category_id: arizona_category.id)
Subcategory.where(name: 'Casa Grande', category_id: arizona_category.id).first_or_create(name: 'Casa Grande', category_id: arizona_category.id)
Subcategory.where(name: 'Flagstaff', category_id: arizona_category.id).first_or_create(name: 'Flagstaff', category_id: arizona_category.id)
Subcategory.where(name: 'Lake Havasu City', category_id: arizona_category.id).first_or_create(name: 'Lake Havasu City', category_id: arizona_category.id)
Subcategory.where(name: 'Phoenix', category_id: arizona_category.id).first_or_create(name: 'Phoenix', category_id: arizona_category.id)
Subcategory.where(name: 'Prescott', category_id: arizona_category.id).first_or_create(name: 'Prescott', category_id: arizona_category.id)
Subcategory.where(name: 'Sierra Vista', category_id: arizona_category.id).first_or_create(name: 'Sierra Vista', category_id: arizona_category.id)
Subcategory.where(name: 'Tucson', category_id: arizona_category.id).first_or_create(name: 'Tucson', category_id: arizona_category.id)
Subcategory.where(name: 'Yuma', category_id: arizona_category.id).first_or_create(name: 'Yuma', category_id: arizona_category.id)

Subcategory.where(name: 'Antioch', category_id: california_category.id).first_or_create(name: 'Antioch', category_id: california_category.id)
Subcategory.where(name: 'Bakersfield', category_id: california_category.id).first_or_create(name: 'Bakersfield', category_id: california_category.id)
Subcategory.where(name: 'Camarillo', category_id: california_category.id).first_or_create(name: 'Camarillo', category_id: california_category.id)
Subcategory.where(name: 'Cathedral City', category_id: california_category.id).first_or_create(name: 'Cathedral City', category_id: california_category.id)
Subcategory.where(name: 'Chico', category_id: california_category.id).first_or_create(name: 'Chico', category_id: california_category.id)
Subcategory.where(name: 'Concord', category_id: california_category.id).first_or_create(name: 'Concord', category_id: california_category.id)
Subcategory.where(name: 'Davis', category_id: california_category.id).first_or_create(name: 'Davis', category_id: california_category.id)
Subcategory.where(name: 'Delano', category_id: california_category.id).first_or_create(name: 'Delano', category_id: california_category.id)
Subcategory.where(name: 'El Centro', category_id: california_category.id).first_or_create(name: 'El Centro', category_id: california_category.id)
Subcategory.where(name: 'Fairfield', category_id: california_category.id).first_or_create(name: 'Fairfield', category_id: california_category.id)
Subcategory.where(name: 'Fresno', category_id: california_category.id).first_or_create(name: 'Fresno', category_id: california_category.id)
Subcategory.where(name: 'Gilroy', category_id: california_category.id).first_or_create(name: 'Gilroy', category_id: california_category.id)
Subcategory.where(name: 'Grover Beach', category_id: california_category.id).first_or_create(name: 'Grover Beach', category_id: california_category.id)
Subcategory.where(name: 'Hanford', category_id: california_category.id).first_or_create(name: 'Hanford', category_id: california_category.id)
Subcategory.where(name: 'Hemet', category_id: california_category.id).first_or_create(name: 'Hemet', category_id: california_category.id)
Subcategory.where(name: 'Lancaster', category_id: california_category.id).first_or_create(name: 'Lancaster', category_id: california_category.id)
Subcategory.where(name: 'Livermore', category_id: california_category.id).first_or_create(name: 'Livermore', category_id: california_category.id)
Subcategory.where(name: 'Lodi', category_id: california_category.id).first_or_create(name: 'Lodi', category_id: california_category.id)
Subcategory.where(name: 'Lompoc', category_id: california_category.id).first_or_create(name: 'Lompoc', category_id: california_category.id)
Subcategory.where(name: 'Los Angeles', category_id: california_category.id).first_or_create(name: 'Los Angeles', category_id: california_category.id)
Subcategory.where(name: 'Madera', category_id: california_category.id).first_or_create(name: 'Madera', category_id: california_category.id)
Subcategory.where(name: 'Manteca', category_id: california_category.id).first_or_create(name: 'Manteca', category_id: california_category.id)
Subcategory.where(name: 'Merced', category_id: california_category.id).first_or_create(name: 'Merced', category_id: california_category.id)
Subcategory.where(name: 'Mission Viejo', category_id: california_category.id).first_or_create(name: 'Mission Viejo', category_id: california_category.id)
Subcategory.where(name: 'Modesto', category_id: california_category.id).first_or_create(name: 'Modesto', category_id: california_category.id)
Subcategory.where(name: 'Napa', category_id: california_category.id).first_or_create(name: 'Napa', category_id: california_category.id)
Subcategory.where(name: 'Oxnard', category_id: california_category.id).first_or_create(name: 'Oxnard', category_id: california_category.id)
Subcategory.where(name: 'Paso de Robles', category_id: california_category.id).first_or_create(name: 'Paso de Robles', category_id: california_category.id)
Subcategory.where(name: 'Petaluma', category_id: california_category.id).first_or_create(name: 'Petaluma', category_id: california_category.id)
Subcategory.where(name: 'Porterville', category_id: california_category.id).first_or_create(name: 'Porterville', category_id: california_category.id)
Subcategory.where(name: 'Redding', category_id: california_category.id).first_or_create(name: 'Redding', category_id: california_category.id)
Subcategory.where(name: 'Sacramento', category_id: california_category.id).first_or_create(name: 'Sacramento', category_id: california_category.id)
Subcategory.where(name: 'Salinas', category_id: california_category.id).first_or_create(name: 'Salinas', category_id: california_category.id)
Subcategory.where(name: 'San Bernardino', category_id: california_category.id).first_or_create(name: 'San Bernardino', category_id: california_category.id)
Subcategory.where(name: 'San Diego', category_id: california_category.id).first_or_create(name: 'San Diego', category_id: california_category.id)
Subcategory.where(name: 'San Francisco', category_id: california_category.id).first_or_create(name: 'San Francisco', category_id: california_category.id)
Subcategory.where(name: 'San Jose', category_id: california_category.id).first_or_create(name: 'San Jose', category_id: california_category.id)
Subcategory.where(name: 'San Luis Obispo', category_id: california_category.id).first_or_create(name: 'San Luis Obispo', category_id: california_category.id)
Subcategory.where(name: 'Santa Barbara', category_id: california_category.id).first_or_create(name: 'Santa Barbara', category_id: california_category.id)
Subcategory.where(name: 'Santa Clarita', category_id: california_category.id).first_or_create(name: 'Santa Clarita', category_id: california_category.id)
Subcategory.where(name: 'Santa Cruz', category_id: california_category.id).first_or_create(name: 'Santa Cruz', category_id: california_category.id)
Subcategory.where(name: 'Santa Maria', category_id: california_category.id).first_or_create(name: 'Santa Maria', category_id: california_category.id)
Subcategory.where(name: 'Santa Rosa', category_id: california_category.id).first_or_create(name: 'Santa Rosa', category_id: california_category.id)
Subcategory.where(name: 'Monterey', category_id: california_category.id).first_or_create(name: 'Monterey', category_id: california_category.id)
Subcategory.where(name: 'Simi Valley', category_id: california_category.id).first_or_create(name: 'Simi Valley', category_id: california_category.id)
Subcategory.where(name: 'Stockton', category_id: california_category.id).first_or_create(name: 'Stockton', category_id: california_category.id)
Subcategory.where(name: 'Temecula', category_id: california_category.id).first_or_create(name: 'Temecula', category_id: california_category.id)
Subcategory.where(name: 'Thousand Oaks', category_id: california_category.id).first_or_create(name: 'Thousand Oaks', category_id: california_category.id)
Subcategory.where(name: 'Tracy', category_id: california_category.id).first_or_create(name: 'Tracy', category_id: california_category.id)
Subcategory.where(name: 'Turlock', category_id: california_category.id).first_or_create(name: 'Turlock', category_id: california_category.id)
Subcategory.where(name: 'Vacaville', category_id: california_category.id).first_or_create(name: 'Vacaville', category_id: california_category.id)
Subcategory.where(name: 'Vallejo', category_id: california_category.id).first_or_create(name: 'Vallejo', category_id: california_category.id)
Subcategory.where(name: 'Victorville', category_id: california_category.id).first_or_create(name: 'Victorville', category_id: california_category.id)
Subcategory.where(name: 'Visalia', category_id: california_category.id).first_or_create(name: 'Visalia', category_id: california_category.id)
Subcategory.where(name: 'Watsonville', category_id: california_category.id).first_or_create(name: 'Watsonville', category_id: california_category.id)
Subcategory.where(name: 'Woodland', category_id: california_category.id).first_or_create(name: 'Woodland', category_id: california_category.id)
Subcategory.where(name: 'Yuba City', category_id: california_category.id).first_or_create(name: 'Yuba City', category_id: california_category.id)

Subcategory.where(name: 'Boulder', category_id: colorado_category.id).first_or_create(name: 'Boulder', category_id: colorado_category.id)
Subcategory.where(name: 'Colorado Springs', category_id: colorado_category.id).first_or_create(name: 'Colorado Springs', category_id: colorado_category.id)
Subcategory.where(name: 'Denver', category_id: colorado_category.id).first_or_create(name: 'Denver', category_id: colorado_category.id)
Subcategory.where(name: 'Fort Collins', category_id: colorado_category.id).first_or_create(name: 'Fort Collins', category_id: colorado_category.id)
Subcategory.where(name: 'Grand Junction', category_id: colorado_category.id).first_or_create(name: 'Grand Junction', category_id: colorado_category.id)
Subcategory.where(name: 'Greeley', category_id: colorado_category.id).first_or_create(name: 'Greeley', category_id: colorado_category.id)
Subcategory.where(name: 'Lafayette', category_id: colorado_category.id).first_or_create(name: 'Lafayette', category_id: colorado_category.id)
Subcategory.where(name: 'Longmont', category_id: colorado_category.id).first_or_create(name: 'Longmont', category_id: colorado_category.id)
Subcategory.where(name: 'Pueblo', category_id: colorado_category.id).first_or_create(name: 'Pueblo', category_id: colorado_category.id)

Subcategory.where(name: 'Danbury', category_id: connecticut_category.id).first_or_create(name: 'Danbury', category_id: connecticut_category.id)
Subcategory.where(name: 'Hartford', category_id: connecticut_category.id).first_or_create(name: 'Hartford', category_id: connecticut_category.id)
Subcategory.where(name: 'New Haven', category_id: connecticut_category.id).first_or_create(name: 'New Haven', category_id: connecticut_category.id)
Subcategory.where(name: 'Norwich', category_id: connecticut_category.id).first_or_create(name: 'Norwich', category_id: connecticut_category.id)
Subcategory.where(name: 'Stamford', category_id: connecticut_category.id).first_or_create(name: 'Stamford', category_id: connecticut_category.id)
Subcategory.where(name: 'Waterbury', category_id: connecticut_category.id).first_or_create(name: 'Waterbury', category_id: connecticut_category.id)

Subcategory.where(name: 'Dover', category_id: delaware_category.id).first_or_create(name: 'Dover', category_id: delaware_category.id)

Subcategory.where(name: 'Bonita Springs', category_id: florida_category.id).first_or_create(name: 'Bonita Springs', category_id: florida_category.id)
Subcategory.where(name: 'Cape Coral', category_id: florida_category.id).first_or_create(name: 'Cape Coral', category_id: florida_category.id)
Subcategory.where(name: 'Daytona Beach', category_id: florida_category.id).first_or_create(name: 'Daytona Beach', category_id: florida_category.id)
Subcategory.where(name: 'Deltona', category_id: florida_category.id).first_or_create(name: 'Deltona', category_id: florida_category.id)
Subcategory.where(name: 'Fort Walton Beach', category_id: florida_category.id).first_or_create(name: 'Fort Walton Beach', category_id: florida_category.id)
Subcategory.where(name: 'Gainesville', category_id: florida_category.id).first_or_create(name: 'Gainesville', category_id: florida_category.id)
Subcategory.where(name: 'Homosassa Springs', category_id: florida_category.id).first_or_create(name: 'Homosassa Springs', category_id: florida_category.id)
Subcategory.where(name: 'Jacksonville', category_id: florida_category.id).first_or_create(name: 'Jacksonville', category_id: florida_category.id)
Subcategory.where(name: 'Kissimmee', category_id: florida_category.id).first_or_create(name: 'Kissimmee', category_id: florida_category.id)
Subcategory.where(name: 'Lady Lake', category_id: florida_category.id).first_or_create(name: 'Lady Lake', category_id: florida_category.id)
Subcategory.where(name: 'Lakeland', category_id: florida_category.id).first_or_create(name: 'Lakeland', category_id: florida_category.id)
Subcategory.where(name: 'Leesburg', category_id: florida_category.id).first_or_create(name: 'Leesburg', category_id: florida_category.id)
Subcategory.where(name: 'Miami', category_id: florida_category.id).first_or_create(name: 'Miami', category_id: florida_category.id)
Subcategory.where(name: 'North Port', category_id: florida_category.id).first_or_create(name: 'North Port', category_id: florida_category.id)
Subcategory.where(name: 'Ocala', category_id: florida_category.id).first_or_create(name: 'Ocala', category_id: florida_category.id)
Subcategory.where(name: 'Orlando', category_id: florida_category.id).first_or_create(name: 'Orlando', category_id: florida_category.id)
Subcategory.where(name: 'Palm Bay', category_id: florida_category.id).first_or_create(name: 'Palm Bay', category_id: florida_category.id)
Subcategory.where(name: 'Panama City', category_id: florida_category.id).first_or_create(name: 'Panama City', category_id: florida_category.id)
Subcategory.where(name: 'Pensacola', category_id: florida_category.id).first_or_create(name: 'Pensacola', category_id: florida_category.id)
Subcategory.where(name: 'Port St. Lucie', category_id: florida_category.id).first_or_create(name: 'Port St. Lucie', category_id: florida_category.id)
Subcategory.where(name: 'Sarasota', category_id: florida_category.id).first_or_create(name: 'Sarasota', category_id: florida_category.id)
Subcategory.where(name: 'Sebastian', category_id: florida_category.id).first_or_create(name: 'Sebastian', category_id: florida_category.id)
Subcategory.where(name: 'Sebring', category_id: florida_category.id).first_or_create(name: 'Sebring', category_id: florida_category.id)
Subcategory.where(name: 'Spring Hill', category_id: florida_category.id).first_or_create(name: 'Spring Hill', category_id: florida_category.id)
Subcategory.where(name: 'St. Augustine', category_id: florida_category.id).first_or_create(name: 'St. Augustine', category_id: florida_category.id)
Subcategory.where(name: 'Tallahassee', category_id: florida_category.id).first_or_create(name: 'Tallahassee', category_id: florida_category.id)
Subcategory.where(name: 'Tampa', category_id: florida_category.id).first_or_create(name: 'Tampa', category_id: florida_category.id)
Subcategory.where(name: 'Titusville', category_id: florida_category.id).first_or_create(name: 'Titusville', category_id: florida_category.id)
Subcategory.where(name: 'Winter Haven', category_id: florida_category.id).first_or_create(name: 'Winter Haven', category_id: florida_category.id)
Subcategory.where(name: 'Zephyrhills', category_id: florida_category.id).first_or_create(name: 'Zephyrhills', category_id: florida_category.id)

Subcategory.where(name: 'Albany', category_id: georgia_category.id).first_or_create(name: 'Albany', category_id: georgia_category.id)
Subcategory.where(name: 'Athens', category_id: georgia_category.id).first_or_create(name: 'Athens', category_id: georgia_category.id)
Subcategory.where(name: 'Atlanta', category_id: georgia_category.id).first_or_create(name: 'Atlanta', category_id: georgia_category.id)
Subcategory.where(name: 'Augusta', category_id: georgia_category.id).first_or_create(name: 'Augusta', category_id: georgia_category.id)
Subcategory.where(name: 'Brunswick', category_id: georgia_category.id).first_or_create(name: 'Brunswick', category_id: georgia_category.id)
Subcategory.where(name: 'Cartersville', category_id: georgia_category.id).first_or_create(name: 'Cartersville', category_id: georgia_category.id)
Subcategory.where(name: 'Columbus', category_id: georgia_category.id).first_or_create(name: 'Columbus', category_id: georgia_category.id)
Subcategory.where(name: 'Dalton', category_id: georgia_category.id).first_or_create(name: 'Dalton', category_id: georgia_category.id)
Subcategory.where(name: 'Gainesville', category_id: georgia_category.id).first_or_create(name: 'Gainesville', category_id: georgia_category.id)
Subcategory.where(name: 'Hinesville', category_id: georgia_category.id).first_or_create(name: 'Hinesville', category_id: georgia_category.id)
Subcategory.where(name: 'Macon', category_id: georgia_category.id).first_or_create(name: 'Macon', category_id: georgia_category.id)
Subcategory.where(name: 'Rome', category_id: georgia_category.id).first_or_create(name: 'Rome', category_id: georgia_category.id)
Subcategory.where(name: 'Savannah', category_id: georgia_category.id).first_or_create(name: 'Savannah', category_id: georgia_category.id)
Subcategory.where(name: 'Valdosta', category_id: georgia_category.id).first_or_create(name: 'Valdosta', category_id: georgia_category.id)
Subcategory.where(name: 'Warner Robins', category_id: georgia_category.id).first_or_create(name: 'Warner Robins', category_id: georgia_category.id)

Subcategory.where(name: 'Kahului', category_id: hawaii_category.id).first_or_create(name: 'Kahului', category_id: hawaii_category.id)
Subcategory.where(name: 'Kailua', category_id: hawaii_category.id).first_or_create(name: 'Kailua', category_id: hawaii_category.id)
Subcategory.where(name: 'Urban Honolulu', category_id: hawaii_category.id).first_or_create(name: 'Urban Honolulu', category_id: hawaii_category.id)

Subcategory.where(name: 'Ames', category_id: iowa_category.id).first_or_create(name: 'Ames', category_id: iowa_category.id)
Subcategory.where(name: 'Cedar Rapids', category_id: iowa_category.id).first_or_create(name: 'Cedar Rapids', category_id: iowa_category.id)
Subcategory.where(name: 'Davenport', category_id: iowa_category.id).first_or_create(name: 'Davenport', category_id: iowa_category.id)
Subcategory.where(name: 'Des Moines', category_id: iowa_category.id).first_or_create(name: 'Des Moines', category_id: iowa_category.id)
Subcategory.where(name: 'Dubuque', category_id: iowa_category.id).first_or_create(name: 'Dubuque', category_id: iowa_category.id)
Subcategory.where(name: 'Iowa City', category_id: iowa_category.id).first_or_create(name: 'Iowa City', category_id: iowa_category.id)
Subcategory.where(name: 'Sioux City', category_id: iowa_category.id).first_or_create(name: 'Sioux City', category_id: iowa_category.id)
Subcategory.where(name: 'Waterloo', category_id: iowa_category.id).first_or_create(name: 'Waterloo', category_id: iowa_category.id)

Subcategory.where(name: 'Boise', category_id: idaho_category.id).first_or_create(name: 'Boise', category_id: idaho_category.id)
Subcategory.where(name: 'Coeur dAlene', category_id: idaho_category.id).first_or_create(name: 'Coeur dAlene', category_id: idaho_category.id)
Subcategory.where(name: 'Idaho Falls', category_id: idaho_category.id).first_or_create(name: 'Idaho Falls', category_id: idaho_category.id)
Subcategory.where(name: 'Lewiston', category_id: idaho_category.id).first_or_create(name: 'Lewiston', category_id: idaho_category.id)
Subcategory.where(name: 'Nampa', category_id: idaho_category.id).first_or_create(name: 'Nampa', category_id: idaho_category.id)
Subcategory.where(name: 'Pocatello', category_id: idaho_category.id).first_or_create(name: 'Pocatello', category_id: idaho_category.id)

Subcategory.where(name: 'Bloomington', category_id: illinois_category.id).first_or_create(name: 'Bloomington', category_id: illinois_category.id)
Subcategory.where(name: 'Carbondale', category_id: illinois_category.id).first_or_create(name: 'Carbondale', category_id: illinois_category.id)
Subcategory.where(name: 'Champaign', category_id: illinois_category.id).first_or_create(name: 'Champaign', category_id: illinois_category.id)
Subcategory.where(name: 'Chicago', category_id: illinois_category.id).first_or_create(name: 'Chicago', category_id: illinois_category.id)
Subcategory.where(name: 'Danville', category_id: illinois_category.id).first_or_create(name: 'Danville', category_id: illinois_category.id)
Subcategory.where(name: 'Decatur', category_id: illinois_category.id).first_or_create(name: 'Decatur', category_id: illinois_category.id)
Subcategory.where(name: 'DeKalb', category_id: illinois_category.id).first_or_create(name: 'DeKalb', category_id: illinois_category.id)
Subcategory.where(name: 'Kankakee', category_id: illinois_category.id).first_or_create(name: 'Kankakee', category_id: illinois_category.id)
Subcategory.where(name: 'Peoria', category_id: illinois_category.id).first_or_create(name: 'Peoria', category_id: illinois_category.id)
Subcategory.where(name: 'Rockford', category_id: illinois_category.id).first_or_create(name: 'Rockford', category_id: illinois_category.id)
Subcategory.where(name: 'Round Lake Beach', category_id: illinois_category.id).first_or_create(name: 'Round Lake Beach', category_id: illinois_category.id)
Subcategory.where(name: 'Springfield', category_id: illinois_category.id).first_or_create(name: 'Springfield', category_id: illinois_category.id)
Subcategory.where(name: 'Alton', category_id: illinois_category.id).first_or_create(name: 'Alton', category_id: illinois_category.id)

Subcategory.where(name: 'Anderson', category_id: indiana_category.id).first_or_create(name: 'Anderson', category_id: indiana_category.id)
Subcategory.where(name: 'Bloomington', category_id: indiana_category.id).first_or_create(name: 'Bloomington', category_id: indiana_category.id)
Subcategory.where(name: 'Columbus', category_id: indiana_category.id).first_or_create(name: 'Columbus', category_id: indiana_category.id)
Subcategory.where(name: 'Elkhart', category_id: indiana_category.id).first_or_create(name: 'Elkhart', category_id: indiana_category.id)
Subcategory.where(name: 'Fort Wayne', category_id: indiana_category.id).first_or_create(name: 'Fort Wayne', category_id: indiana_category.id)
Subcategory.where(name: 'Indianapolis', category_id: indiana_category.id).first_or_create(name: 'Indianapolis', category_id: indiana_category.id)
Subcategory.where(name: 'Kokomo', category_id: indiana_category.id).first_or_create(name: 'Kokomo', category_id: indiana_category.id)
Subcategory.where(name: 'Lafayette', category_id: indiana_category.id).first_or_create(name: 'Lafayette', category_id: indiana_category.id)
Subcategory.where(name: 'Michigan City', category_id: indiana_category.id).first_or_create(name: 'Michigan City', category_id: indiana_category.id)
Subcategory.where(name: 'Muncie', category_id: indiana_category.id).first_or_create(name: 'Muncie', category_id: indiana_category.id)
Subcategory.where(name: 'South Bend', category_id: indiana_category.id).first_or_create(name: 'South Bend', category_id: indiana_category.id)
Subcategory.where(name: 'Terre Haute', category_id: indiana_category.id).first_or_create(name: 'Terre Haute', category_id: indiana_category.id)

Subcategory.where(name: 'Lawrence', category_id: kansas_category.id).first_or_create(name: 'Lawrence', category_id: kansas_category.id)
Subcategory.where(name: 'Manhattan', category_id: kansas_category.id).first_or_create(name: 'Manhattan', category_id: kansas_category.id)
Subcategory.where(name: 'Topeka', category_id: kansas_category.id).first_or_create(name: 'Topeka', category_id: kansas_category.id)
Subcategory.where(name: 'Wichita', category_id: kansas_category.id).first_or_create(name: 'Wichita', category_id: kansas_category.id)

Subcategory.where(name: 'Bowling Green', category_id: kentucky_category.id).first_or_create(name: 'Bowling Green', category_id: kentucky_category.id)
Subcategory.where(name: 'Lexington-Fayette', category_id: kentucky_category.id).first_or_create(name: 'Lexington-Fayette', category_id: kentucky_category.id)
Subcategory.where(name: 'Louisville', category_id: kentucky_category.id).first_or_create(name: 'Louisville', category_id: kentucky_category.id)
Subcategory.where(name: 'Owensboro', category_id: kentucky_category.id).first_or_create(name: 'Owensboro', category_id: kentucky_category.id)
Subcategory.where(name: 'Radcliff', category_id: kentucky_category.id).first_or_create(name: 'Radcliff', category_id: kentucky_category.id)

Subcategory.where(name: 'Alexandria', category_id: louisiana_category.id).first_or_create(name: 'Alexandria', category_id: louisiana_category.id)
Subcategory.where(name: 'Baton Rouge', category_id: louisiana_category.id).first_or_create(name: 'Baton Rouge', category_id: louisiana_category.id)
Subcategory.where(name: 'Hammond', category_id: louisiana_category.id).first_or_create(name: 'Hammond', category_id: louisiana_category.id)
Subcategory.where(name: 'Houma', category_id: louisiana_category.id).first_or_create(name: 'Houma', category_id: louisiana_category.id)
Subcategory.where(name: 'Lafayette', category_id: louisiana_category.id).first_or_create(name: 'Lafayette', category_id: louisiana_category.id)
Subcategory.where(name: 'Lake Charles', category_id: louisiana_category.id).first_or_create(name: 'Lake Charles', category_id: louisiana_category.id)
Subcategory.where(name: 'Mandeville', category_id: louisiana_category.id).first_or_create(name: 'Mandeville', category_id: louisiana_category.id)
Subcategory.where(name: 'Monroe', category_id: louisiana_category.id).first_or_create(name: 'Monroe', category_id: louisiana_category.id)
Subcategory.where(name: 'New Orleans', category_id: louisiana_category.id).first_or_create(name: 'New Orleans', category_id: louisiana_category.id)
Subcategory.where(name: 'Shreveport', category_id: louisiana_category.id).first_or_create(name: 'Shreveport', category_id: louisiana_category.id)
Subcategory.where(name: 'Slidell', category_id: louisiana_category.id).first_or_create(name: 'Slidell', category_id: louisiana_category.id)
Subcategory.where(name: 'Barnstable Town', category_id: louisiana_category.id).first_or_create(name: 'Barnstable Town', category_id: louisiana_category.id)

Subcategory.where(name: 'Boston', category_id: massachusetts_category.id).first_or_create(name: 'Boston', category_id: massachusetts_category.id)
Subcategory.where(name: 'Leominster', category_id: massachusetts_category.id).first_or_create(name: 'Leominster', category_id: massachusetts_category.id)
Subcategory.where(name: 'New Bedford', category_id: massachusetts_category.id).first_or_create(name: 'New Bedford', category_id: massachusetts_category.id)
Subcategory.where(name: 'Pittsfield', category_id: massachusetts_category.id).first_or_create(name: 'Pittsfield', category_id: massachusetts_category.id)
Subcategory.where(name: 'Springfield', category_id: massachusetts_category.id).first_or_create(name: 'Springfield', category_id: massachusetts_category.id)
Subcategory.where(name: 'Worcester', category_id: massachusetts_category.id).first_or_create(name: 'Worcester', category_id: massachusetts_category.id)

Subcategory.where(name: 'Aberdeen', category_id: maryland_category.id).first_or_create(name: 'Aberdeen', category_id: maryland_category.id)
Subcategory.where(name: 'Baltimore', category_id: maryland_category.id).first_or_create(name: 'Baltimore', category_id: maryland_category.id)
Subcategory.where(name: 'Cumberland', category_id: maryland_category.id).first_or_create(name: 'Cumberland', category_id: maryland_category.id)
Subcategory.where(name: 'Frederick', category_id: maryland_category.id).first_or_create(name: 'Frederick', category_id: maryland_category.id)
Subcategory.where(name: 'Hagerstown', category_id: maryland_category.id).first_or_create(name: 'Hagerstown', category_id: maryland_category.id)
Subcategory.where(name: 'Lexington Park', category_id: maryland_category.id).first_or_create(name: 'Lexington Park', category_id: maryland_category.id)
Subcategory.where(name: 'Salisbury', category_id: maryland_category.id).first_or_create(name: 'Salisbury', category_id: maryland_category.id)
Subcategory.where(name: 'Waldorf', category_id: maryland_category.id).first_or_create(name: 'Waldorf', category_id: maryland_category.id)
Subcategory.where(name: 'Westminster', category_id: maryland_category.id).first_or_create(name: 'Westminster', category_id: maryland_category.id)

Subcategory.where(name: 'Bangor', category_id: maine_category.id).first_or_create(name: 'Bangor', category_id: maine_category.id)
Subcategory.where(name: 'Lewiston', category_id: maine_category.id).first_or_create(name: 'Lewiston', category_id: maine_category.id)
Subcategory.where(name: 'Portland', category_id: maine_category.id).first_or_create(name: 'Portland', category_id: maine_category.id)

Subcategory.where(name: 'Ann Arbor', category_id: michigan_category.id).first_or_create(name: 'Ann Arbor', category_id: michigan_category.id)
Subcategory.where(name: 'Battle Creek', category_id: michigan_category.id).first_or_create(name: 'Battle Creek', category_id: michigan_category.id)
Subcategory.where(name: 'Bay City', category_id: michigan_category.id).first_or_create(name: 'Bay City', category_id: michigan_category.id)
Subcategory.where(name: 'Benton Harbor', category_id: michigan_category.id).first_or_create(name: 'Benton Harbor', category_id: michigan_category.id)
Subcategory.where(name: 'Detroit', category_id: michigan_category.id).first_or_create(name: 'Detroit', category_id: michigan_category.id)
Subcategory.where(name: 'Flint', category_id: michigan_category.id).first_or_create(name: 'Flint', category_id: michigan_category.id)
Subcategory.where(name: 'Grand Rapids', category_id: michigan_category.id).first_or_create(name: 'Grand Rapids', category_id: michigan_category.id)
Subcategory.where(name: 'Holland', category_id: michigan_category.id).first_or_create(name: 'Holland', category_id: michigan_category.id)
Subcategory.where(name: 'Jackson', category_id: michigan_category.id).first_or_create(name: 'Jackson', category_id: michigan_category.id)
Subcategory.where(name: 'Kalamazoo', category_id: michigan_category.id).first_or_create(name: 'Kalamazoo', category_id: michigan_category.id)
Subcategory.where(name: 'Lansing', category_id: michigan_category.id).first_or_create(name: 'Lansing', category_id: michigan_category.id)
Subcategory.where(name: 'Midland', category_id: michigan_category.id).first_or_create(name: 'Midland', category_id: michigan_category.id)
Subcategory.where(name: 'Monroe', category_id: michigan_category.id).first_or_create(name: 'Monroe', category_id: michigan_category.id)
Subcategory.where(name: 'Muskegon', category_id: michigan_category.id).first_or_create(name: 'Muskegon', category_id: michigan_category.id)
Subcategory.where(name: 'Port Huron', category_id: michigan_category.id).first_or_create(name: 'Port Huron', category_id: michigan_category.id)
Subcategory.where(name: 'Saginaw', category_id: michigan_category.id).first_or_create(name: 'Saginaw', category_id: michigan_category.id)
Subcategory.where(name: 'South Lyon', category_id: michigan_category.id).first_or_create(name: 'South Lyon', category_id: michigan_category.id)

Subcategory.where(name: 'Duluth', category_id: minnesota_category.id).first_or_create(name: 'Duluth', category_id: minnesota_category.id)
Subcategory.where(name: 'Mankato', category_id: minnesota_category.id).first_or_create(name: 'Mankato', category_id: minnesota_category.id)
Subcategory.where(name: 'Minneapolis', category_id: minnesota_category.id).first_or_create(name: 'Minneapolis', category_id: minnesota_category.id)
Subcategory.where(name: 'Rochester', category_id: minnesota_category.id).first_or_create(name: 'Rochester', category_id: minnesota_category.id)
Subcategory.where(name: 'St. Cloud', category_id: minnesota_category.id).first_or_create(name: 'St. Cloud', category_id: minnesota_category.id)

Subcategory.where(name: 'Cape Girardeau', category_id: missouri_category.id).first_or_create(name: 'Cape Girardeau', category_id: missouri_category.id)
Subcategory.where(name: 'Columbia', category_id: missouri_category.id).first_or_create(name: 'Columbia', category_id: missouri_category.id)
Subcategory.where(name: 'Jefferson City', category_id: missouri_category.id).first_or_create(name: 'Jefferson City', category_id: missouri_category.id)
Subcategory.where(name: 'Joplin', category_id: missouri_category.id).first_or_create(name: 'Joplin', category_id: missouri_category.id)
Subcategory.where(name: 'Kansas City', category_id: missouri_category.id).first_or_create(name: 'Kansas City', category_id: missouri_category.id)
Subcategory.where(name: 'Lees Summit', category_id: missouri_category.id).first_or_create(name: 'Lees Summit', category_id: missouri_category.id)
Subcategory.where(name: 'Springfield', category_id: missouri_category.id).first_or_create(name: 'Springfield', category_id: missouri_category.id)
Subcategory.where(name: 'St. Joseph', category_id: missouri_category.id).first_or_create(name: 'St. Joseph', category_id: missouri_category.id)
Subcategory.where(name: 'St. Louis', category_id: missouri_category.id).first_or_create(name: 'St. Louis', category_id: missouri_category.id)

Subcategory.where(name: 'Gulfport', category_id: mississippi_category.id).first_or_create(name: 'Gulfport', category_id: mississippi_category.id)
Subcategory.where(name: 'Hattiesburg', category_id: mississippi_category.id).first_or_create(name: 'Hattiesburg', category_id: mississippi_category.id)
Subcategory.where(name: 'Jackson', category_id: mississippi_category.id).first_or_create(name: 'Jackson', category_id: mississippi_category.id)
Subcategory.where(name: 'Pascagoula', category_id: mississippi_category.id).first_or_create(name: 'Pascagoula', category_id: mississippi_category.id)
Subcategory.where(name: 'Billings', category_id: montana_category.id).first_or_create(name: 'Billings', category_id: montana_category.id)

Subcategory.where(name: 'Great Falls', category_id: montana_category.id).first_or_create(name: 'Great Falls', category_id: montana_category.id)
Subcategory.where(name: 'Missoula', category_id: montana_category.id).first_or_create(name: 'Missoula', category_id: montana_category.id)

Subcategory.where(name: 'Asheville', category_id: northcarolina_category.id).first_or_create(name: 'Asheville', category_id: northcarolina_category.id)
Subcategory.where(name: 'Burlington', category_id: northcarolina_category.id).first_or_create(name: 'Burlington', category_id: northcarolina_category.id)
Subcategory.where(name: 'Concord', category_id: northcarolina_category.id).first_or_create(name: 'Concord', category_id: northcarolina_category.id)
Subcategory.where(name: 'Durham', category_id: northcarolina_category.id).first_or_create(name: 'Durham', category_id: northcarolina_category.id)
Subcategory.where(name: 'Fayetteville', category_id: northcarolina_category.id).first_or_create(name: 'Fayetteville', category_id: northcarolina_category.id)
Subcategory.where(name: 'Gastonia', category_id: northcarolina_category.id).first_or_create(name: 'Gastonia', category_id: northcarolina_category.id)
Subcategory.where(name: 'Goldsboro', category_id: northcarolina_category.id).first_or_create(name: 'Goldsboro', category_id: northcarolina_category.id)
Subcategory.where(name: 'Greensboro', category_id: northcarolina_category.id).first_or_create(name: 'Greensboro', category_id: northcarolina_category.id)
Subcategory.where(name: 'Greenville', category_id: northcarolina_category.id).first_or_create(name: 'Greenville', category_id: northcarolina_category.id)
Subcategory.where(name: 'Hickory', category_id: northcarolina_category.id).first_or_create(name: 'Hickory', category_id: northcarolina_category.id)
Subcategory.where(name: 'High Point', category_id: northcarolina_category.id).first_or_create(name: 'High Point', category_id: northcarolina_category.id)
Subcategory.where(name: 'Jacksonville', category_id: northcarolina_category.id).first_or_create(name: 'Jacksonville', category_id: northcarolina_category.id)
Subcategory.where(name: 'New Bern', category_id: northcarolina_category.id).first_or_create(name: 'New Bern', category_id: northcarolina_category.id)
Subcategory.where(name: 'Raleigh', category_id: northcarolina_category.id).first_or_create(name: 'Raleigh', category_id: northcarolina_category.id)
Subcategory.where(name: 'Rocky Mount', category_id: northcarolina_category.id).first_or_create(name: 'Rocky Mount', category_id: northcarolina_category.id)
Subcategory.where(name: 'Wilmington', category_id: northcarolina_category.id).first_or_create(name: 'Wilmington', category_id: northcarolina_category.id)
Subcategory.where(name: 'Winston-Salem', category_id: northcarolina_category.id).first_or_create(name: 'Winston-Salem', category_id: northcarolina_category.id)
Subcategory.where(name: 'Charlotte', category_id: northcarolina_category.id).first_or_create(name: 'Charlotte', category_id: northcarolina_category.id)

Subcategory.where(name: 'Bismarck', category_id: northdakota_category.id).first_or_create(name: 'Bismarck', category_id: northdakota_category.id)
Subcategory.where(name: 'Fargo', category_id: northdakota_category.id).first_or_create(name: 'Fargo', category_id: northdakota_category.id)
Subcategory.where(name: 'Grand Forks', category_id: northdakota_category.id).first_or_create(name: 'Grand Forks', category_id: northdakota_category.id)

Subcategory.where(name: 'Grand Island', category_id: nebraska_category.id).first_or_create(name: 'Grand Island', category_id: nebraska_category.id)
Subcategory.where(name: 'Lincoln', category_id: nebraska_category.id).first_or_create(name: 'Lincoln', category_id: nebraska_category.id)
Subcategory.where(name: 'Omaha', category_id: nebraska_category.id).first_or_create(name: 'Omaha', category_id: nebraska_category.id)

Subcategory.where(name: 'Manchester', category_id: newhampshire_category.id).first_or_create(name: 'Manchester', category_id: newhampshire_category.id)
Subcategory.where(name: 'Nashua', category_id: newhampshire_category.id).first_or_create(name: 'Nashua', category_id: newhampshire_category.id)
Subcategory.where(name: 'Portsmouth', category_id: newhampshire_category.id).first_or_create(name: 'Portsmouth', category_id: newhampshire_category.id)
Subcategory.where(name: 'Rochester', category_id: newhampshire_category.id).first_or_create(name: 'Rochester', category_id: newhampshire_category.id)

Subcategory.where(name: 'Atlantic City', category_id: newjersey_category.id).first_or_create(name: 'Atlantic City', category_id: newjersey_category.id)
Subcategory.where(name: 'Hightstown', category_id: newjersey_category.id).first_or_create(name: 'Hightstown', category_id: newjersey_category.id)
Subcategory.where(name: 'Trenton', category_id: newjersey_category.id).first_or_create(name: 'Trenton', category_id: newjersey_category.id)
Subcategory.where(name: 'Villas', category_id: newjersey_category.id).first_or_create(name: 'Villas', category_id: newjersey_category.id)
Subcategory.where(name: 'Vineland', category_id: newjersey_category.id).first_or_create(name: 'Vineland', category_id: newjersey_category.id)

Subcategory.where(name: 'Albuquerque', category_id: newmexico_category.id).first_or_create(name: 'Albuquerque', category_id: newmexico_category.id)
Subcategory.where(name: 'Farmington', category_id: newmexico_category.id).first_or_create(name: 'Farmington', category_id: newmexico_category.id)
Subcategory.where(name: 'Las Cruces', category_id: newmexico_category.id).first_or_create(name: 'Las Cruces', category_id: newmexico_category.id)
Subcategory.where(name: 'Los Lunas', category_id: newmexico_category.id).first_or_create(name: 'Los Lunas', category_id: newmexico_category.id)
Subcategory.where(name: 'Santa Fe', category_id: newmexico_category.id).first_or_create(name: 'Santa Fe', category_id: newmexico_category.id)

Subcategory.where(name: 'Carson City', category_id: nevada_category.id).first_or_create(name: 'Carson City', category_id: nevada_category.id)
Subcategory.where(name: 'Las Vegas', category_id: nevada_category.id).first_or_create(name: 'Las Vegas', category_id: nevada_category.id)
Subcategory.where(name: 'Reno', category_id: nevada_category.id).first_or_create(name: 'Reno', category_id: nevada_category.id)
Subcategory.where(name: 'Elko', category_id: nevada_category.id).first_or_create(name: 'Elko', category_id: nevada_category.id)

Subcategory.where(name: 'Albany', category_id: newyork_category.id).first_or_create(name: 'Albany', category_id: newyork_category.id)
Subcategory.where(name: 'Binghamton', category_id: newyork_category.id).first_or_create(name: 'Binghamton', category_id: newyork_category.id)
Subcategory.where(name: 'Buffalo', category_id: newyork_category.id).first_or_create(name: 'Buffalo', category_id: newyork_category.id)
Subcategory.where(name: 'Elmira', category_id: newyork_category.id).first_or_create(name: 'Elmira', category_id: newyork_category.id)
Subcategory.where(name: 'Glens Falls', category_id: newyork_category.id).first_or_create(name: 'Glens Falls', category_id: newyork_category.id)
Subcategory.where(name: 'Ithaca', category_id: newyork_category.id).first_or_create(name: 'Ithaca', category_id: newyork_category.id)
Subcategory.where(name: 'Kingston', category_id: newyork_category.id).first_or_create(name: 'Kingston', category_id: newyork_category.id)
Subcategory.where(name: 'Middletown', category_id: newyork_category.id).first_or_create(name: 'Middletown', category_id: newyork_category.id)
Subcategory.where(name: 'New York', category_id: newyork_category.id).first_or_create(name: 'New York', category_id: newyork_category.id)
Subcategory.where(name: 'Poughkeepsie', category_id: newyork_category.id).first_or_create(name: 'Poughkeepsie', category_id: newyork_category.id)
Subcategory.where(name: 'Rochester', category_id: newyork_category.id).first_or_create(name: 'Rochester', category_id: newyork_category.id)
Subcategory.where(name: 'Saratoga Springs', category_id: newyork_category.id).first_or_create(name: 'Saratoga Springs', category_id: newyork_category.id)
Subcategory.where(name: 'Syracuse', category_id: newyork_category.id).first_or_create(name: 'Syracuse', category_id: newyork_category.id)
Subcategory.where(name: 'Utica', category_id: newyork_category.id).first_or_create(name: 'Utica', category_id: newyork_category.id)
Subcategory.where(name: 'Watertown', category_id: newyork_category.id).first_or_create(name: 'Watertown', category_id: newyork_category.id)

Subcategory.where(name: 'Akron', category_id: ohio_category.id).first_or_create(name: 'Akron', category_id: ohio_category.id)
Subcategory.where(name: 'Canton', category_id: ohio_category.id).first_or_create(name: 'Canton', category_id: ohio_category.id)
Subcategory.where(name: 'Cincinnati', category_id: ohio_category.id).first_or_create(name: 'Cincinnati', category_id: ohio_category.id)
Subcategory.where(name: 'Cleveland', category_id: ohio_category.id).first_or_create(name: 'Cleveland', category_id: ohio_category.id)
Subcategory.where(name: 'Columbus', category_id: ohio_category.id).first_or_create(name: 'Columbus', category_id: ohio_category.id)
Subcategory.where(name: 'Dayton', category_id: ohio_category.id).first_or_create(name: 'Dayton', category_id: ohio_category.id)
Subcategory.where(name: 'Lima', category_id: ohio_category.id).first_or_create(name: 'Lima', category_id: ohio_category.id)
Subcategory.where(name: 'Lorain', category_id: ohio_category.id).first_or_create(name: 'Lorain', category_id: ohio_category.id)
Subcategory.where(name: 'Mansfield', category_id: ohio_category.id).first_or_create(name: 'Mansfield', category_id: ohio_category.id)
Subcategory.where(name: 'Middletown', category_id: ohio_category.id).first_or_create(name: 'Middletown', category_id: ohio_category.id)
Subcategory.where(name: 'Newark', category_id: ohio_category.id).first_or_create(name: 'Newark', category_id: ohio_category.id)
Subcategory.where(name: 'Springfield', category_id: ohio_category.id).first_or_create(name: 'Springfield', category_id: ohio_category.id)
Subcategory.where(name: 'Toledo', category_id: ohio_category.id).first_or_create(name: 'Toledo', category_id: ohio_category.id)
Subcategory.where(name: 'Youngstown', category_id: ohio_category.id).first_or_create(name: 'Youngstown', category_id: ohio_category.id)

Subcategory.where(name: 'Lawton', category_id: oklahoma_category.id).first_or_create(name: 'Lawton', category_id: oklahoma_category.id)
Subcategory.where(name: 'Norman', category_id: oklahoma_category.id).first_or_create(name: 'Norman', category_id: oklahoma_category.id)
Subcategory.where(name: 'Oklahoma City', category_id: oklahoma_category.id).first_or_create(name: 'Oklahoma City', category_id: oklahoma_category.id)
Subcategory.where(name: 'Tulsa', category_id: oklahoma_category.id).first_or_create(name: 'Tulsa', category_id: oklahoma_category.id)

Subcategory.where(name: 'Albany', category_id: oregon_category.id).first_or_create(name: 'Albany', category_id: oregon_category.id)
Subcategory.where(name: 'Bend', category_id: oregon_category.id).first_or_create(name: 'Bend', category_id: oregon_category.id)
Subcategory.where(name: 'Corvallis', category_id: oregon_category.id).first_or_create(name: 'Corvallis', category_id: oregon_category.id)
Subcategory.where(name: 'Eugene', category_id: oregon_category.id).first_or_create(name: 'Eugene', category_id: oregon_category.id)
Subcategory.where(name: 'Grants Pass', category_id: oregon_category.id).first_or_create(name: 'Grants Pass', category_id: oregon_category.id)
Subcategory.where(name: 'Medford', category_id: oregon_category.id).first_or_create(name: 'Medford', category_id: oregon_category.id)
Subcategory.where(name: 'Portland', category_id: oregon_category.id).first_or_create(name: 'Portland', category_id: oregon_category.id)
Subcategory.where(name: 'Salem', category_id: oregon_category.id).first_or_create(name: 'Salem', category_id: oregon_category.id)

Subcategory.where(name: 'Allentown', category_id: pennsylvania_category.id).first_or_create(name: 'Allentown', category_id: pennsylvania_category.id)
Subcategory.where(name: 'Altoona', category_id: pennsylvania_category.id).first_or_create(name: 'Altoona', category_id: pennsylvania_category.id)
Subcategory.where(name: 'Bloomsburg', category_id: pennsylvania_category.id).first_or_create(name: 'Bloomsburg', category_id: pennsylvania_category.id)
Subcategory.where(name: 'Chambersburg', category_id: pennsylvania_category.id).first_or_create(name: 'Chambersburg', category_id: pennsylvania_category.id)
Subcategory.where(name: 'East Stroudsburg', category_id: pennsylvania_category.id).first_or_create(name: 'East Stroudsburg', category_id: pennsylvania_category.id)
Subcategory.where(name: 'Erie', category_id: pennsylvania_category.id).first_or_create(name: 'Erie', category_id: pennsylvania_category.id)
Subcategory.where(name: 'Hanover', category_id: pennsylvania_category.id).first_or_create(name: 'Hanover', category_id: pennsylvania_category.id)
Subcategory.where(name: 'Harrisburg', category_id: pennsylvania_category.id).first_or_create(name: 'Harrisburg', category_id: pennsylvania_category.id)
Subcategory.where(name: 'Hazleton', category_id: pennsylvania_category.id).first_or_create(name: 'Hazleton', category_id: pennsylvania_category.id)
Subcategory.where(name: 'Johnstown', category_id: pennsylvania_category.id).first_or_create(name: 'Johnstown', category_id: pennsylvania_category.id)
Subcategory.where(name: 'Lancaster', category_id: pennsylvania_category.id).first_or_create(name: 'Lancaster', category_id: pennsylvania_category.id)
Subcategory.where(name: 'Lebanon', category_id: pennsylvania_category.id).first_or_create(name: 'Lebanon', category_id: pennsylvania_category.id)
Subcategory.where(name: 'Monessen', category_id: pennsylvania_category.id).first_or_create(name: 'Monessen', category_id: pennsylvania_category.id)
Subcategory.where(name: 'Philadelphia', category_id: pennsylvania_category.id).first_or_create(name: 'Philadelphia', category_id: pennsylvania_category.id)
Subcategory.where(name: 'Pittsburgh', category_id: pennsylvania_category.id).first_or_create(name: 'Pittsburgh', category_id: pennsylvania_category.id)
Subcategory.where(name: 'Pottstown', category_id: pennsylvania_category.id).first_or_create(name: 'Pottstown', category_id: pennsylvania_category.id)
Subcategory.where(name: 'Reading', category_id: pennsylvania_category.id).first_or_create(name: 'Reading', category_id: pennsylvania_category.id)
Subcategory.where(name: 'Scranton', category_id: pennsylvania_category.id).first_or_create(name: 'Scranton', category_id: pennsylvania_category.id)
Subcategory.where(name: 'State College', category_id: pennsylvania_category.id).first_or_create(name: 'State College', category_id: pennsylvania_category.id)
Subcategory.where(name: 'Uniontown', category_id: pennsylvania_category.id).first_or_create(name: 'Uniontown', category_id: pennsylvania_category.id)
Subcategory.where(name: 'Williamsport', category_id: pennsylvania_category.id).first_or_create(name: 'Williamsport', category_id: pennsylvania_category.id)
Subcategory.where(name: 'York', category_id: pennsylvania_category.id).first_or_create(name: 'York', category_id: pennsylvania_category.id)

Subcategory.where(name: 'Aguadilla', category_id: puertorico_category.id).first_or_create(name: 'Aguadilla', category_id: puertorico_category.id)
Subcategory.where(name: 'Arecibo', category_id: puertorico_category.id).first_or_create(name: 'Arecibo', category_id: puertorico_category.id)
Subcategory.where(name: 'Barceloneta', category_id: puertorico_category.id).first_or_create(name: 'Barceloneta', category_id: puertorico_category.id)
Subcategory.where(name: 'Fajardo', category_id: puertorico_category.id).first_or_create(name: 'Fajardo', category_id: puertorico_category.id)
Subcategory.where(name: 'Guayama', category_id: puertorico_category.id).first_or_create(name: 'Guayama', category_id: puertorico_category.id)
Subcategory.where(name: 'Juana Díaz', category_id: puertorico_category.id).first_or_create(name: 'Juana Díaz', category_id: puertorico_category.id)
Subcategory.where(name: 'Mayagüez', category_id: puertorico_category.id).first_or_create(name: 'Mayagüez', category_id: puertorico_category.id)
Subcategory.where(name: 'Ponce', category_id: puertorico_category.id).first_or_create(name: 'Ponce', category_id: puertorico_category.id)
Subcategory.where(name: 'San German', category_id: puertorico_category.id).first_or_create(name: 'San German', category_id: puertorico_category.id)
Subcategory.where(name: 'San Juan', category_id: puertorico_category.id).first_or_create(name: 'San Juan', category_id: puertorico_category.id)
Subcategory.where(name: 'Yauco', category_id: puertorico_category.id).first_or_create(name: 'Yauco', category_id: puertorico_category.id)

Subcategory.where(name: 'Providence', category_id: rhodeisland_category.id).first_or_create(name: 'Providence', category_id: rhodeisland_category.id)

Subcategory.where(name: 'Anderson', category_id: southcarolina_category.id).first_or_create(name: 'Anderson', category_id: southcarolina_category.id)
Subcategory.where(name: 'Charleston', category_id: southcarolina_category.id).first_or_create(name: 'Charleston', category_id: southcarolina_category.id)
Subcategory.where(name: 'Columbia', category_id: southcarolina_category.id).first_or_create(name: 'Columbia', category_id: southcarolina_category.id)
Subcategory.where(name: 'Florence', category_id: southcarolina_category.id).first_or_create(name: 'Florence', category_id: southcarolina_category.id)
Subcategory.where(name: 'Greenville', category_id: southcarolina_category.id).first_or_create(name: 'Greenville', category_id: southcarolina_category.id)
Subcategory.where(name: 'Hilton Head Island', category_id: southcarolina_category.id).first_or_create(name: 'Hilton Head Island', category_id: southcarolina_category.id)
Subcategory.where(name: 'Mauldin', category_id: southcarolina_category.id).first_or_create(name: 'Mauldin', category_id: southcarolina_category.id)
Subcategory.where(name: 'Myrtle Beach', category_id: southcarolina_category.id).first_or_create(name: 'Myrtle Beach', category_id: southcarolina_category.id)
Subcategory.where(name: 'Rock Hill', category_id: southcarolina_category.id).first_or_create(name: 'Rock Hill', category_id: southcarolina_category.id)
Subcategory.where(name: 'Spartanburg', category_id: southcarolina_category.id).first_or_create(name: 'Spartanburg', category_id: southcarolina_category.id)
Subcategory.where(name: 'Sumter', category_id: southcarolina_category.id).first_or_create(name: 'Sumter', category_id: southcarolina_category.id)

Subcategory.where(name: 'Rapid City', category_id: southdakota_category.id).first_or_create(name: 'Rapid City', category_id: southdakota_category.id)
Subcategory.where(name: 'Sioux Falls', category_id: southdakota_category.id).first_or_create(name: 'Sioux Falls', category_id: southdakota_category.id)

Subcategory.where(name: 'Bristol', category_id: tennessee_category.id).first_or_create(name: 'Bristol', category_id: tennessee_category.id)
Subcategory.where(name: 'Chattanooga', category_id: tennessee_category.id).first_or_create(name: 'Chattanooga', category_id: tennessee_category.id)
Subcategory.where(name: 'Clarksville', category_id: tennessee_category.id).first_or_create(name: 'Clarksville', category_id: tennessee_category.id)
Subcategory.where(name: 'Cleveland', category_id: tennessee_category.id).first_or_create(name: 'Cleveland', category_id: tennessee_category.id)
Subcategory.where(name: 'Jackson', category_id: tennessee_category.id).first_or_create(name: 'Jackson', category_id: tennessee_category.id)
Subcategory.where(name: 'Johnson City', category_id: tennessee_category.id).first_or_create(name: 'Johnson City', category_id: tennessee_category.id)
Subcategory.where(name: 'Kingsport', category_id: tennessee_category.id).first_or_create(name: 'Kingsport', category_id: tennessee_category.id)
Subcategory.where(name: 'Knoxville', category_id: tennessee_category.id).first_or_create(name: 'Knoxville', category_id: tennessee_category.id)
Subcategory.where(name: 'Memphis', category_id: tennessee_category.id).first_or_create(name: 'Memphis', category_id: tennessee_category.id)
Subcategory.where(name: 'Morristown', category_id: tennessee_category.id).first_or_create(name: 'Morristown', category_id: tennessee_category.id)
Subcategory.where(name: 'Murfreesboro', category_id: tennessee_category.id).first_or_create(name: 'Murfreesboro', category_id: tennessee_category.id)
Subcategory.where(name: 'Nashville', category_id: tennessee_category.id).first_or_create(name: 'Nashville', category_id: tennessee_category.id)

Subcategory.where(name: 'Abilene', category_id: texas_category.id).first_or_create(name: 'Abilene', category_id: texas_category.id)
Subcategory.where(name: 'Amarillo', category_id: texas_category.id).first_or_create(name: 'Amarillo', category_id: texas_category.id)
Subcategory.where(name: 'Angleton', category_id: texas_category.id).first_or_create(name: 'Angleton', category_id: texas_category.id)
Subcategory.where(name: 'Austin', category_id: texas_category.id).first_or_create(name: 'Austin', category_id: texas_category.id)
Subcategory.where(name: 'Beaumont', category_id: texas_category.id).first_or_create(name: 'Beaumont', category_id: texas_category.id)
Subcategory.where(name: 'Brownsville', category_id: texas_category.id).first_or_create(name: 'Brownsville', category_id: texas_category.id)
Subcategory.where(name: 'College Station', category_id: texas_category.id).first_or_create(name: 'College Station', category_id: texas_category.id)
Subcategory.where(name: 'Corpus Christi', category_id: texas_category.id).first_or_create(name: 'Corpus Christi', category_id: texas_category.id)
Subcategory.where(name: 'Dallas', category_id: texas_category.id).first_or_create(name: 'Dallas', category_id: texas_category.id)
Subcategory.where(name: 'Denton', category_id: texas_category.id).first_or_create(name: 'Denton', category_id: texas_category.id)
Subcategory.where(name: 'El Paso', category_id: texas_category.id).first_or_create(name: 'El Paso', category_id: texas_category.id)
Subcategory.where(name: 'Harlingen', category_id: texas_category.id).first_or_create(name: 'Harlingen', category_id: texas_category.id)
Subcategory.where(name: 'Houston', category_id: texas_category.id).first_or_create(name: 'Houston', category_id: texas_category.id)
Subcategory.where(name: 'Killeen', category_id: texas_category.id).first_or_create(name: 'Killeen', category_id: texas_category.id)
Subcategory.where(name: 'Laredo', category_id: texas_category.id).first_or_create(name: 'Laredo', category_id: texas_category.id)
Subcategory.where(name: 'Longview', category_id: texas_category.id).first_or_create(name: 'Longview', category_id: texas_category.id)
Subcategory.where(name: 'Lubbock', category_id: texas_category.id).first_or_create(name: 'Lubbock', category_id: texas_category.id)
Subcategory.where(name: 'McAllen', category_id: texas_category.id).first_or_create(name: 'McAllen', category_id: texas_category.id)
Subcategory.where(name: 'McKinney', category_id: texas_category.id).first_or_create(name: 'McKinney', category_id: texas_category.id)
Subcategory.where(name: 'Midland', category_id: texas_category.id).first_or_create(name: 'Midland', category_id: texas_category.id)
Subcategory.where(name: 'Odessa', category_id: texas_category.id).first_or_create(name: 'Odessa', category_id: texas_category.id)
Subcategory.where(name: 'Port Arthur', category_id: texas_category.id).first_or_create(name: 'Port Arthur', category_id: texas_category.id)
Subcategory.where(name: 'San Angelo', category_id: texas_category.id).first_or_create(name: 'San Angelo', category_id: texas_category.id)
Subcategory.where(name: 'San Antonio', category_id: texas_category.id).first_or_create(name: 'San Antonio', category_id: texas_category.id)
Subcategory.where(name: 'San Marcos', category_id: texas_category.id).first_or_create(name: 'San Marcos', category_id: texas_category.id)
Subcategory.where(name: 'Sherman', category_id: texas_category.id).first_or_create(name: 'Sherman', category_id: texas_category.id)
Subcategory.where(name: 'Temple', category_id: texas_category.id).first_or_create(name: 'Temple', category_id: texas_category.id)
Subcategory.where(name: 'Texarkana', category_id: texas_category.id).first_or_create(name: 'Texarkana', category_id: texas_category.id)
Subcategory.where(name: 'Texas City', category_id: texas_category.id).first_or_create(name: 'Texas City', category_id: texas_category.id)
Subcategory.where(name: 'The Woodlands', category_id: texas_category.id).first_or_create(name: 'The Woodlands', category_id: texas_category.id)
Subcategory.where(name: 'Tyler', category_id: texas_category.id).first_or_create(name: 'Tyler', category_id: texas_category.id)
Subcategory.where(name: 'Victoria', category_id: texas_category.id).first_or_create(name: 'Victoria', category_id: texas_category.id)
Subcategory.where(name: 'Waco', category_id: texas_category.id).first_or_create(name: 'Waco', category_id: texas_category.id)
Subcategory.where(name: 'Wichita Falls', category_id: texas_category.id).first_or_create(name: 'Wichita Falls', category_id: texas_category.id)

Subcategory.where(name: 'Logan', category_id: utah_category.id).first_or_create(name: 'Logan', category_id: utah_category.id)
Subcategory.where(name: 'Ogden', category_id: utah_category.id).first_or_create(name: 'Ogden', category_id: utah_category.id)
Subcategory.where(name: 'Provo', category_id: utah_category.id).first_or_create(name: 'Provo', category_id: utah_category.id)
Subcategory.where(name: 'Salt Lake City', category_id: utah_category.id).first_or_create(name: 'Salt Lake City', category_id: utah_category.id)
Subcategory.where(name: 'St. George', category_id: utah_category.id).first_or_create(name: 'St. George', category_id: utah_category.id)

Subcategory.where(name: 'Blacksburg', category_id: virginia_category.id).first_or_create(name: 'Blacksburg', category_id: virginia_category.id)
Subcategory.where(name: 'Charlottesville', category_id: virginia_category.id).first_or_create(name: 'Charlottesville', category_id: virginia_category.id)
Subcategory.where(name: 'Fredericksburg', category_id: virginia_category.id).first_or_create(name: 'Fredericksburg', category_id: virginia_category.id)
Subcategory.where(name: 'Harrisonburg', category_id: virginia_category.id).first_or_create(name: 'Harrisonburg', category_id: virginia_category.id)
Subcategory.where(name: 'Lynchburg', category_id: virginia_category.id).first_or_create(name: 'Lynchburg', category_id: virginia_category.id)
Subcategory.where(name: 'Richmond', category_id: virginia_category.id).first_or_create(name: 'Richmond', category_id: virginia_category.id)
Subcategory.where(name: 'Roanoke', category_id: virginia_category.id).first_or_create(name: 'Roanoke', category_id: virginia_category.id)
Subcategory.where(name: 'Staunton', category_id: virginia_category.id).first_or_create(name: 'Staunton', category_id: virginia_category.id)
Subcategory.where(name: 'Virginia Beach', category_id: virginia_category.id).first_or_create(name: 'Virginia Beach', category_id: virginia_category.id)
Subcategory.where(name: 'Williamsburg', category_id: virginia_category.id).first_or_create(name: 'Williamsburg', category_id: virginia_category.id)
Subcategory.where(name: 'Winchester', category_id: virginia_category.id).first_or_create(name: 'Winchester', category_id: virginia_category.id)

Subcategory.where(name: 'Burlington', category_id: vermont_category.id).first_or_create(name: 'Burlington', category_id: vermont_category.id)

Subcategory.where(name: 'Bellingham', category_id: washington_category.id).first_or_create(name: 'Bellingham', category_id: washington_category.id)
Subcategory.where(name: 'Bremerton', category_id: washington_category.id).first_or_create(name: 'Bremerton', category_id: washington_category.id)
Subcategory.where(name: 'Kennewick', category_id: washington_category.id).first_or_create(name: 'Kennewick', category_id: washington_category.id)
Subcategory.where(name: 'Longview', category_id: washington_category.id).first_or_create(name: 'Longview', category_id: washington_category.id)
Subcategory.where(name: 'Marysville', category_id: washington_category.id).first_or_create(name: 'Marysville', category_id: washington_category.id)
Subcategory.where(name: 'Mount Vernon', category_id: washington_category.id).first_or_create(name: 'Mount Vernon', category_id: washington_category.id)
Subcategory.where(name: 'Olympia', category_id: washington_category.id).first_or_create(name: 'Olympia', category_id: washington_category.id)
Subcategory.where(name: 'Seattle', category_id: washington_category.id).first_or_create(name: 'Seattle', category_id: washington_category.id)
Subcategory.where(name: 'Spokane', category_id: washington_category.id).first_or_create(name: 'Spokane', category_id: washington_category.id)
Subcategory.where(name: 'Walla Walla', category_id: washington_category.id).first_or_create(name: 'Walla Walla', category_id: washington_category.id)
Subcategory.where(name: 'Wenatchee', category_id: washington_category.id).first_or_create(name: 'Wenatchee', category_id: washington_category.id)
Subcategory.where(name: 'Yakima', category_id: washington_category.id).first_or_create(name: 'Yakima', category_id: washington_category.id)

Subcategory.where(name: 'Appleton', category_id: wisconsin_category.id).first_or_create(name: 'Appleton', category_id: wisconsin_category.id)
Subcategory.where(name: 'Beloit', category_id: wisconsin_category.id).first_or_create(name: 'Beloit', category_id: wisconsin_category.id)
Subcategory.where(name: 'Eau Claire', category_id: wisconsin_category.id).first_or_create(name: 'Eau Claire', category_id: wisconsin_category.id)
Subcategory.where(name: 'Fond du Lac', category_id: wisconsin_category.id).first_or_create(name: 'Fond du Lac', category_id: wisconsin_category.id)
Subcategory.where(name: 'Green Bay', category_id: wisconsin_category.id).first_or_create(name: 'Green Bay', category_id: wisconsin_category.id)
Subcategory.where(name: 'Janesville', category_id: wisconsin_category.id).first_or_create(name: 'Janesville', category_id: wisconsin_category.id)
Subcategory.where(name: 'Kenosha', category_id: wisconsin_category.id).first_or_create(name: 'Kenosha', category_id: wisconsin_category.id)
Subcategory.where(name: 'La Crosse', category_id: wisconsin_category.id).first_or_create(name: 'La Crosse', category_id: wisconsin_category.id)
Subcategory.where(name: 'Madison', category_id: wisconsin_category.id).first_or_create(name: 'Madison', category_id: wisconsin_category.id)
Subcategory.where(name: 'Milwaukee', category_id: wisconsin_category.id).first_or_create(name: 'Milwaukee', category_id: wisconsin_category.id)
Subcategory.where(name: 'Oshkosh', category_id: wisconsin_category.id).first_or_create(name: 'Oshkosh', category_id: wisconsin_category.id)
Subcategory.where(name: 'Racine', category_id: wisconsin_category.id).first_or_create(name: 'Racine', category_id: wisconsin_category.id)
Subcategory.where(name: 'Sheboygan', category_id: wisconsin_category.id).first_or_create(name: 'Sheboygan', category_id: wisconsin_category.id)
Subcategory.where(name: 'Wausau', category_id: wisconsin_category.id).first_or_create(name: 'Wausau', category_id: wisconsin_category.id)
Subcategory.where(name: 'West Bend', category_id: wisconsin_category.id).first_or_create(name: 'West Bend', category_id: wisconsin_category.id)

Subcategory.where(name: 'Beckley', category_id: westvirginia_category.id).first_or_create(name: 'Beckley', category_id: westvirginia_category.id)
Subcategory.where(name: 'Charleston', category_id: westvirginia_category.id).first_or_create(name: 'Charleston', category_id: westvirginia_category.id)
Subcategory.where(name: 'Huntington', category_id: westvirginia_category.id).first_or_create(name: 'Huntington', category_id: westvirginia_category.id)
Subcategory.where(name: 'Morgantown', category_id: westvirginia_category.id).first_or_create(name: 'Morgantown', category_id: westvirginia_category.id)
Subcategory.where(name: 'Parkersburg', category_id: westvirginia_category.id).first_or_create(name: 'Parkersburg', category_id: westvirginia_category.id)
Subcategory.where(name: 'Weirton', category_id: westvirginia_category.id).first_or_create(name: 'Weirton', category_id: westvirginia_category.id)
Subcategory.where(name: 'Wheeling', category_id: westvirginia_category.id).first_or_create(name: 'Wheeling', category_id: westvirginia_category.id)

Subcategory.where(name: 'Casper', category_id: wyoming_category.id).first_or_create(name: 'Casper', category_id: wyoming_category.id)
Subcategory.where(name: 'Cheyenne', category_id: wyoming_category.id).first_or_create(name: 'Cheyenne', category_id: wyoming_category.id)